title: Daniel Moses - Portfolios
email: danielscottmoses@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the dual portfolio of Daniel Moses. This website serves as both a lighting designer portfolio and a computer science portfolio for Daniel Moses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  iban1223

# Build settings
theme: jekyll-theme-midnight 
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
    - Gemfile
    - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
